"""initial schema

Revision ID: 6060d287acbf
Revises: 
Create Date: 2026-07-16 15:15:31.273242

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6060d287acbf'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('display_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('account_behavioral_contexts',
    sa.Column('context_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dna_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history_depth', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('context_id'),
    sa.UniqueConstraint('account_id', 'version', name='uq_account_context_version')
    )
    op.create_index(op.f('ix_account_behavioral_contexts_account_id'), 'account_behavioral_contexts', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_behavioral_contexts_customer_id'), 'account_behavioral_contexts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_account_behavioral_contexts_is_current'), 'account_behavioral_contexts', ['is_current'], unique=False)
    op.create_table('behavioral_dna_profiles',
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dna_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trusted_beneficiaries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history_depth', sa.Integer(), nullable=False),
    sa.Column('behavioral_risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('changed_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('prev_version_hash', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('customer_id', 'version', name='uq_customer_profile_version')
    )
    op.create_index(op.f('ix_behavioral_dna_profiles_customer_id'), 'behavioral_dna_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_behavioral_dna_profiles_is_current'), 'behavioral_dna_profiles', ['is_current'], unique=False)
    op.create_table('customer_account_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'account_id', name='uq_customer_account')
    )
    op.create_index(op.f('ix_customer_account_links_account_id'), 'customer_account_links', ['account_id'], unique=True)
    op.create_index(op.f('ix_customer_account_links_customer_id'), 'customer_account_links', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_account_links_customer_id'), table_name='customer_account_links')
    op.drop_index(op.f('ix_customer_account_links_account_id'), table_name='customer_account_links')
    op.drop_table('customer_account_links')
    op.drop_index(op.f('ix_behavioral_dna_profiles_is_current'), table_name='behavioral_dna_profiles')
    op.drop_index(op.f('ix_behavioral_dna_profiles_customer_id'), table_name='behavioral_dna_profiles')
    op.drop_table('behavioral_dna_profiles')
    op.drop_index(op.f('ix_account_behavioral_contexts_is_current'), table_name='account_behavioral_contexts')
    op.drop_index(op.f('ix_account_behavioral_contexts_customer_id'), table_name='account_behavioral_contexts')
    op.drop_index(op.f('ix_account_behavioral_contexts_account_id'), table_name='account_behavioral_contexts')
    op.drop_table('account_behavioral_contexts')
    op.drop_table('customers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
