"""backfill checkpoints and source_tx_id

Revision ID: a1cd0ea8d74e
Revises: 6060d287acbf
Create Date: 2026-07-16 15:42:45.598532

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1cd0ea8d74e'
down_revision: str | None = '6060d287acbf'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_checkpoints',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('csv_path', sa.String(), nullable=False),
    sa.Column('byte_offset', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('last_tx_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.add_column('account_behavioral_contexts', sa.Column('source_tx_id', sa.String(), nullable=True))
    op.add_column('behavioral_dna_profiles', sa.Column('source_tx_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavioral_dna_profiles', 'source_tx_id')
    op.drop_column('account_behavioral_contexts', 'source_tx_id')
    op.drop_table('backfill_checkpoints')
    # ### end Alembic commands ###
