"""token generation station

Revision ID: c7a3f9d2e1b4
Revises: a1cd0ea8d74e
Create Date: 2026-07-17 09:15:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'c7a3f9d2e1b4'
down_revision: str | None = 'a1cd0ea8d74e'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_registry',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('receiver_account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('behavioral_status', sa.String(), nullable=False),
    sa.Column('graph_status', sa.String(), nullable=False),
    sa.Column('trust_status', sa.String(), nullable=False),
    sa.Column('compliance_status', sa.String(), nullable=False),
    sa.Column('decision_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_token_registry_account_id'), 'token_registry', ['account_id'], unique=False)
    op.create_index(op.f('ix_token_registry_customer_id'), 'token_registry', ['customer_id'], unique=False)

    op.create_table('token_audit_events',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['token_registry.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_audit_events_transaction_id'), 'token_audit_events', ['transaction_id'], unique=False)

    op.create_table('token_stage_results',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['token_registry.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'stage', name='uq_token_stage')
    )
    op.create_index(op.f('ix_token_stage_results_transaction_id'), 'token_stage_results', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_stage_results_transaction_id'), table_name='token_stage_results')
    op.drop_table('token_stage_results')
    op.drop_index(op.f('ix_token_audit_events_transaction_id'), table_name='token_audit_events')
    op.drop_table('token_audit_events')
    op.drop_index(op.f('ix_token_registry_customer_id'), table_name='token_registry')
    op.drop_index(op.f('ix_token_registry_account_id'), table_name='token_registry')
    op.drop_table('token_registry')
    # ### end Alembic commands ###
